import {
  LayoutDashboard,
  Lightbulb,
  Landmark,
  Goal,
  FileText,
  Clock,
  SaudiRiyalIcon,
  Briefcase,
  Users,
  Import,
  ChartBar,
  ChartLine,
  Workflow,
} from 'lucide-react';

export const ADMIN_PRIVATE_ROUTES = [
  {
    id: 0,
    path: `/login`,
    key: 'login',
    label: 'Login',
    element: 'LoginPage',
    icon: LayoutDashboard,
    showInSidebar: false,
  },
  {
    id: 1,
    path: `/user-management`,
    key: 'user-management',
    label: 'User Management',
    element: 'UserManagement',
    icon: Users,
    showInSidebar: true,
  },
  
  {
    id: 2,
    path: `/user-management/add-user`,
    key: 'add-user',
    label: 'Add User',
    element: 'AddUser',
    icon: Users,
    showInSidebar: false,
  },
  {
    id: 3,
    path: `/user-management/add-external-user`,
    key: 'add-external-user',
    label: 'Add External User',
    element: 'AddExternalUser',
    icon: Users,
    showInSidebar: false,
  },
  {
    id: 4,
    path: `/user-management/edit-user/:id`,
    key: 'edit-user',
    label: 'Edit User',
    element: 'EditUser2',
    icon: Users,
    showInSidebar: false,
  },
];
