export const PERMISSIONS = {
  // Committee Management
  COMM_CREATE: 'COMM_CREATE',
  COMM_EDIT: 'COMM_EDIT',
  COMM_DELETE: 'COMM_DELETE',
  COMM_VIEW: 'COMM_VIEW',

  // Member Management
  MEMBER_CREATE: 'MEMBER_CREATE',
  MEMBER_DELETE: 'MEMBER_DELETE',
  MEMBER_CHANGE_UPDATE: 'MEMBER_CHANGE_UPDATE',

  // Document Management
  DOC_VIEW: 'DOC_VIEW',
  DOC_UPLOAD_CREATE: 'DOC_UPLOAD_CREATE',
  DOC_DELETE: 'DOC_DELETE',

  // Meeting Management
  MEETING_CREATE: 'MEETING_CREATE',
  MEETING_EDIT: 'MEETING_EDIT',
  MEETING_CANCEL: 'MEETING_CANCEL',
  MEETING_VIEW: 'MEETING_VIEW',
  MEETING_START: 'MEETING_START',
  MEETING_MANAGE_ATTENDANCE: 'MEETING_MANAGE_ATTENDANCE',
  MEETING_AGENDA_ADD: 'MEETING_AGENDA_ADD',
  MEETING_AGENDA_EDIT: 'MEETING_AGENDA_EDIT',
  MEETING_AGENDA_DELETE: 'MEETING_AGENDA_DELETE',
  MEETING_NOTES_CREATE: 'MEETING_NOTES_CREATE',
  MEETING_FILE_UPLOAD_CREATE: 'MEETING_FILE_UPLOAD_CREATE',
  MEETING_FILE_DELETE: 'MEETING_FILE_DELETE',
  MEETING_MOM_PUBLISH_CREATE: 'MEETING_MOM_PUBLISH_CREATE',
  MEETING_MOM_EDIT: 'MEETING_MOM_EDIT',
  MEETING_MOM_DELETE: 'MEETING_MOM_DELETE',

  // Decision Management
  DECISION_CREATE: 'DECISION_CREATE',
  DECISION_EDIT: 'DECISION_EDIT',
  DECISION_DELETE: 'DECISION_DELETE',
  DECISION_VIEW: 'DECISION_VIEW',
  DECISION_ASSIGN: 'DECISION_ASSIGN',
  DECISION_TRACK: 'DECISION_TRACK',
  DECISION_COMPLETE: 'DECISION_COMPLETE',

  // Voting Management
  VOTE_CREATE: 'VOTE_CREATE',
  VOTE_PARTICIPATE: 'VOTE_PARTICIPATE',
  VOTE_CLOSE: 'VOTE_CLOSE',
  VOTE_REOPEN: 'VOTE_REOPEN',
  VOTE_VIEW_RESULTS: 'VOTE_VIEW_RESULTS',

  // Task Management
  TASK_CREATE: 'TASK_CREATE',
  TASK_EDIT: 'TASK_EDIT',
  TASK_DELETE: 'TASK_DELETE',
  TASK_VIEW: 'TASK_VIEW',
  TASK_ASSIGN: 'TASK_ASSIGN',
  TASK_CHANGE_STATUS: 'TASK_CHANGE_STATUS',
  TASK_FILE_UPLOAD: 'TASK_FILE_UPLOAD',
  TASK_FILE_DELETE: 'TASK_FILE_DELETE',
  TASK_COMMENT: 'TASK_COMMENT',

  // Calendar Management
  CALENDAR_VIEW: 'CALENDAR_VIEW',
  CALENDAR_SYNC: 'CALENDAR_SYNC',

  // News Management
  NEWS_CREATE: 'NEWS_CREATE',
  NEWS_EDIT: 'NEWS_EDIT',
  NEWS_DELETE: 'NEWS_DELETE',
  NEWS_VIEW: 'NEWS_VIEW',
  NEWS_SEND_NOTIFICATION: 'NEWS_SEND_NOTIFICATION',

  // Request Management
  REQUEST_CREATE: 'REQUEST_CREATE',
  REQUEST_VIEW: 'REQUEST_VIEW',
  REQUEST_APPROVE_REJECT: 'REQUEST_APPROVE_REJECT',

  // System Admin
  PERMISSION_MANAGE: 'PERMISSION_MANAGE',
  ROLE_MANAGE: 'ROLE_MANAGE',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  USER_MANAGE: 'USER_MANAGE',

  // Council Management
  COUNCIL_CREATE: 'COUNCIL_CREATE',
  COUNCIL_EDIT: 'COUNCIL_EDIT',
  COUNCIL_DELETE: 'COUNCIL_DELETE',
};

// Group permissions by module for easier management
export const PERMISSION_MODULES = {
  'Committee Management': [PERMISSIONS.COMM_CREATE, PERMISSIONS.COMM_EDIT, PERMISSIONS.COMM_DELETE, PERMISSIONS.COMM_VIEW],
  'Member Management': [PERMISSIONS.MEMBER_ADD, PERMISSIONS.MEMBER_REMOVE, PERMISSIONS.MEMBER_CHANGE_ROLE],
  'Document Management': [PERMISSIONS.DOC_VIEW, PERMISSIONS.DOC_UPLOAD, PERMISSIONS.DOC_DELETE],
  'Meeting Management': [
    PERMISSIONS.MEETING_CREATE,
    PERMISSIONS.MEETING_EDIT,
    PERMISSIONS.MEETING_CANCEL,
    PERMISSIONS.MEETING_VIEW,
    PERMISSIONS.MEETING_START,
    PERMISSIONS.MEETING_MANAGE_ATTENDANCE,
    PERMISSIONS.MEETING_AGENDA_ADD,
    PERMISSIONS.MEETING_AGENDA_EDIT,
    PERMISSIONS.MEETING_AGENDA_DELETE,
    PERMISSIONS.MEETING_NOTES_ADD,
    PERMISSIONS.MEETING_FILE_UPLOAD,
    PERMISSIONS.MEETING_FILE_DELETE,
    PERMISSIONS.MEETING_MOM_PUBLISH,
    PERMISSIONS.MEETING_MOM_EDIT,
    PERMISSIONS.MEETING_MOM_DELETE,
  ],
  'Decision Management': [
    PERMISSIONS.DECISION_CREATE,
    PERMISSIONS.DECISION_EDIT,
    PERMISSIONS.DECISION_DELETE,
    PERMISSIONS.DECISION_VIEW,
    PERMISSIONS.DECISION_ASSIGN,
    PERMISSIONS.DECISION_TRACK,
    PERMISSIONS.DECISION_COMPLETE,
  ],
  'Voting Management': [PERMISSIONS.VOTE_CREATE, PERMISSIONS.VOTE_PARTICIPATE, PERMISSIONS.VOTE_CLOSE, PERMISSIONS.VOTE_REOPEN, PERMISSIONS.VOTE_VIEW_RESULTS],
  'Task Management': [
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_CHANGE_STATUS,
    PERMISSIONS.TASK_FILE_UPLOAD,
    PERMISSIONS.TASK_FILE_DELETE,
    PERMISSIONS.TASK_COMMENT,
  ],
  'Calendar Management': [PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.CALENDAR_SYNC],
  'News Management': [PERMISSIONS.NEWS_CREATE, PERMISSIONS.NEWS_EDIT, PERMISSIONS.NEWS_DELETE, PERMISSIONS.NEWS_VIEW, PERMISSIONS.NEWS_SEND_NOTIFICATION],
  'Request Management': [PERMISSIONS.REQUEST_CREATE, PERMISSIONS.REQUEST_VIEW, PERMISSIONS.REQUEST_APPROVE_REJECT],
  'System Admin': [PERMISSIONS.PERMISSION_MANAGE, PERMISSIONS.ROLE_MANAGE, PERMISSIONS.AUDIT_LOG_VIEW, PERMISSIONS.USER_MANAGE],
  'Council Management': [PERMISSIONS.COUNCIL_CREATE, PERMISSIONS.COUNCIL_EDIT, PERMISSIONS.COUNCIL_DELETE],
};

// Permission types for UI display
export const PERMISSION_TYPES = {
  CREATE: 'CREATE',
  EDIT: 'EDIT',
  DELETE: 'DELETE',
  VIEW: 'VIEW',
  EXPORT: 'EXPORT',
};

// Helper function to get permission display name
export const getPermissionDisplayName = permission => {
  const type = permission.split('_').pop();
  return type.charAt(0).toUpperCase() + type.slice(1).toLowerCase();
};

// Helper function to get module name from permission
export const getModuleFromPermission = permission => {
  const parts = permission.split('_');
  if (parts.length >= 2) {
    const moduleParts = parts.slice(0, -1);
    return moduleParts.map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase()).join(' ');
  }
  return 'Unknown Module';
};
